# Generated by Django 2.0.2 on 2018-03-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junrei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isGuest',
            field=models.BooleanField(default=False),
        ),
    ]
